<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image\Icon\add.gif" />
    <None Remove="Image\Icon\add.png" />
    <None Remove="Image\Icon\addressbook.gif" />
    <None Remove="Image\Icon\alert.gif" />
    <None Remove="Image\Icon\apple.gif" />
    <None Remove="Image\Icon\arrow1_e.gif" />
    <None Remove="Image\Icon\arrow1_n.gif" />
    <None Remove="Image\Icon\arrow1_ne.gif" />
    <None Remove="Image\Icon\arrow1_nw.gif" />
    <None Remove="Image\Icon\arrow1_s.gif" />
    <None Remove="Image\Icon\arrow1_se.gif" />
    <None Remove="Image\Icon\arrow1_sw.gif" />
    <None Remove="Image\Icon\arrow1_w.gif" />
    <None Remove="Image\Icon\arrow2_e.gif" />
    <None Remove="Image\Icon\arrow2_n.gif" />
    <None Remove="Image\Icon\arrow2_ne.gif" />
    <None Remove="Image\Icon\arrow2_nw.gif" />
    <None Remove="Image\Icon\arrow2_s.gif" />
    <None Remove="Image\Icon\arrow2_se.gif" />
    <None Remove="Image\Icon\arrow2_sw.gif" />
    <None Remove="Image\Icon\arrow2_w.gif" />
    <None Remove="Image\Icon\arrow3_e.gif" />
    <None Remove="Image\Icon\arrow3_n.gif" />
    <None Remove="Image\Icon\arrow3_ne.gif" />
    <None Remove="Image\Icon\arrow3_nw.gif" />
    <None Remove="Image\Icon\arrow3_s.gif" />
    <None Remove="Image\Icon\arrow3_se.gif" />
    <None Remove="Image\Icon\arrow3_sw.gif" />
    <None Remove="Image\Icon\arrow3_w.gif" />
    <None Remove="Image\Icon\arrow_right.gif" />
    <None Remove="Image\Icon\ascii.gif" />
    <None Remove="Image\Icon\ascii.png" />
    <None Remove="Image\Icon\back.gif" />
    <None Remove="Image\Icon\bigsmile.gif" />
    <None Remove="Image\Icon\binary.gif" />
    <None Remove="Image\Icon\blah.gif" />
    <None Remove="Image\Icon\bstop.gif" />
    <None Remove="Image\Icon\buy.gif" />
    <None Remove="Image\Icon\calday.gif" />
    <None Remove="Image\Icon\calendar.gif" />
    <None Remove="Image\Icon\camera.gif" />
    <None Remove="Image\Icon\cart.gif" />
    <None Remove="Image\Icon\cd.gif" />
    <None Remove="Image\Icon\cellphone.gif" />
    <None Remove="Image\Icon\chat.gif" />
    <None Remove="Image\Icon\check.gif" />
    <None Remove="Image\Icon\checkout-orange.gif" />
    <None Remove="Image\Icon\close.gif" />
    <None Remove="Image\Icon\comment.gif" />
    <None Remove="Image\Icon\contact-new.png" />
    <None Remove="Image\Icon\cube.gif" />
    <None Remove="Image\Icon\database_(edit)_16x16.gif" />
    <None Remove="Image\Icon\Date-Add.png" />
    <None Remove="Image\Icon\Date-Delete.png" />
    <None Remove="Image\Icon\Date-Edit.png" />
    <None Remove="Image\Icon\Date-Error.png" />
    <None Remove="Image\Icon\Date-Go.png" />
    <None Remove="Image\Icon\Date-Link.png" />
    <None Remove="Image\Icon\Date-Magnify.png" />
    <None Remove="Image\Icon\Date-Next.png" />
    <None Remove="Image\Icon\Date-Previous.png" />
    <None Remove="Image\Icon\date.png" />
    <None Remove="Image\Icon\date2.gif" />
    <None Remove="Image\Icon\day.gif" />
    <None Remove="Image\Icon\DBTable.png" />
    <None Remove="Image\Icon\delete.png" />
    <None Remove="Image\Icon\denied.gif" />
    <None Remove="Image\Icon\Disk.png" />
    <None Remove="Image\Icon\document-open.png" />
    <None Remove="Image\Icon\document-save16.png" />
    <None Remove="Image\Icon\document-save22.png" />
    <None Remove="Image\Icon\document-save24.png" />
    <None Remove="Image\Icon\Document-Todo-32.png" />
    <None Remove="Image\Icon\Document-Todo2-32.png" />
    <None Remove="Image\Icon\document.gif" />
    <None Remove="Image\Icon\Documents .png" />
    <None Remove="Image\Icon\download.gif" />
    <None Remove="Image\Icon\drive-harddisk.png" />
    <None Remove="Image\Icon\drive-removable-media.png" />
    <None Remove="Image\Icon\edit-redo.png" />
    <None Remove="Image\Icon\edit.gif" />
    <None Remove="Image\Icon\edit.png" />
    <None Remove="Image\Icon\eject.gif" />
    <None Remove="Image\Icon\equalizer.gif" />
    <None Remove="Image\Icon\exit.png" />
    <None Remove="Image\Icon\Find.png" />
    <None Remove="Image\Icon\first.gif" />
    <None Remove="Image\Icon\flag.gif" />
    <None Remove="Image\Icon\flash.gif" />
    <None Remove="Image\Icon\Folder-Add.png" />
    <None Remove="Image\Icon\Folder-Delete.png" />
    <None Remove="Image\Icon\Folder-Find.png" />
    <None Remove="Image\Icon\folder.gif" />
    <None Remove="Image\Icon\Folder.png" />
    <None Remove="Image\Icon\forward.gif" />
    <None Remove="Image\Icon\frown.gif" />
    <None Remove="Image\Icon\ftp.gif" />
    <None Remove="Image\Icon\gnome-run.ico" />
    <None Remove="Image\Icon\go-last.png" />
    <None Remove="Image\Icon\go-next.png" />
    <None Remove="Image\Icon\graph.gif" />
    <None Remove="Image\Icon\heart.gif" />
    <None Remove="Image\Icon\home.gif" />
    <None Remove="Image\Icon\Home_icon.png" />
    <None Remove="Image\Icon\html.gif" />
    <None Remove="Image\Icon\icon_user.gif" />
    <None Remove="Image\Icon\icon_wand.gif" />
    <None Remove="Image\Icon\ico_datemask.png" />
    <None Remove="Image\Icon\ipod.gif" />
    <None Remove="Image\Icon\last.gif" />
    <None Remove="Image\Icon\Layer-Create.png" />
    <None Remove="Image\Icon\list.png" />
    <None Remove="Image\Icon\List_Icon.png" />
    <None Remove="Image\Icon\lock.gif" />
    <None Remove="Image\Icon\loop.gif" />
    <None Remove="Image\Icon\mail.gif" />
    <None Remove="Image\Icon\man.gif" />
    <None Remove="Image\Icon\manman.gif" />
    <None Remove="Image\Icon\Monitor-Window-3d.png" />
    <None Remove="Image\Icon\music.gif" />
    <None Remove="Image\Icon\mute.gif" />
    <None Remove="Image\Icon\mute_centered.gif" />
    <None Remove="Image\Icon\My-Documents-Inside-Green-128.png" />
    <None Remove="Image\Icon\newwindow.gif" />
    <None Remove="Image\Icon\next.gif" />
    <None Remove="Image\Icon\night.gif" />
    <None Remove="Image\Icon\open.gif" />
    <None Remove="Image\Icon\pause.gif" />
    <None Remove="Image\Icon\pdf.png" />
    <None Remove="Image\Icon\phone.gif" />
    <None Remove="Image\Icon\play.gif" />
    <None Remove="Image\Icon\preferences-desktop.png" />
    <None Remove="Image\Icon\previous.gif" />
    <None Remove="Image\Icon\quicktime.gif" />
    <None Remove="Image\Icon\redo.gif" />
    <None Remove="Image\Icon\reload.gif" />
    <None Remove="Image\Icon\sad.gif" />
    <None Remove="Image\Icon\save.gif" />
    <None Remove="Image\Icon\save16.png" />
    <None Remove="Image\Icon\save24.png" />
    <None Remove="Image\Icon\scream.gif" />
    <None Remove="Image\Icon\search.gif" />
    <None Remove="Image\Icon\search.png" />
    <None Remove="Image\Icon\seconds.gif" />
    <None Remove="Image\Icon\Setting-Tools.png" />
    <None Remove="Image\Icon\setup.png" />
    <None Remove="Image\Icon\smile.gif" />
    <None Remove="Image\Icon\smirk.gif" />
    <None Remove="Image\Icon\star.gif" />
    <None Remove="Image\Icon\stop.gif" />
    <None Remove="Image\Icon\subtract.gif" />
    <None Remove="Image\Icon\support2_(edit)_16x16.gif" />
    <None Remove="Image\Icon\switch.gif" />
    <None Remove="Image\Icon\system-users.png" />
    <None Remove="Image\Icon\Table-Delete.png" />
    <None Remove="Image\Icon\target.gif" />
    <None Remove="Image\Icon\tcp.gif" />
    <None Remove="Image\Icon\text-x-changelog.png" />
    <None Remove="Image\Icon\text-x-script.png" />
    <None Remove="Image\Icon\text-x-source.png" />
    <None Remove="Image\Icon\TextTemplate.ico" />
    <None Remove="Image\Icon\time.gif" />
    <None Remove="Image\Icon\titlewindow.gif" />
    <None Remove="Image\Icon\toggle.gif" />
    <None Remove="Image\Icon\tongue.gif" />
    <None Remove="Image\Icon\tools.gif" />
    <None Remove="Image\Icon\trackback.gif" />
    <None Remove="Image\Icon\trash.gif" />
    <None Remove="Image\Icon\tree.png" />
    <None Remove="Image\Icon\tv.gif" />
    <None Remove="Image\Icon\type.gif" />
    <None Remove="Image\Icon\undo.gif" />
    <None Remove="Image\Icon\unlock.gif" />
    <None Remove="Image\Icon\upload.gif" />
    <None Remove="Image\Icon\user.gif" />
    <None Remove="Image\Icon\video.gif" />
    <None Remove="Image\Icon\view_tree.png" />
    <None Remove="Image\Icon\volume.gif" />
    <None Remove="Image\Icon\volume_high.gif" />
    <None Remove="Image\Icon\volume_low.gif" />
    <None Remove="Image\Icon\Wand.png" />
    <None Remove="Image\Icon\wifi.gif" />
    <None Remove="Image\Icon\window.gif" />
    <None Remove="Image\Icon\woman.gif" />
    <None Remove="Image\Icon\womanman.gif" />
    <None Remove="Image\Icon\work.gif" />
    <None Remove="Image\Icon\zoomin.gif" />
    <None Remove="Image\Icon\zoomout.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Image\Icon\add.gif" />
    <Resource Include="Image\Icon\add.png" />
    <Resource Include="Image\Icon\addressbook.gif" />
    <Resource Include="Image\Icon\alert.gif" />
    <Resource Include="Image\Icon\apple.gif" />
    <Resource Include="Image\Icon\arrow1_e.gif" />
    <Resource Include="Image\Icon\arrow1_n.gif" />
    <Resource Include="Image\Icon\arrow1_ne.gif" />
    <Resource Include="Image\Icon\arrow1_nw.gif" />
    <Resource Include="Image\Icon\arrow1_s.gif" />
    <Resource Include="Image\Icon\arrow1_se.gif" />
    <Resource Include="Image\Icon\arrow1_sw.gif" />
    <Resource Include="Image\Icon\arrow1_w.gif" />
    <Resource Include="Image\Icon\arrow2_e.gif" />
    <Resource Include="Image\Icon\arrow2_n.gif" />
    <Resource Include="Image\Icon\arrow2_ne.gif" />
    <Resource Include="Image\Icon\arrow2_nw.gif" />
    <Resource Include="Image\Icon\arrow2_s.gif" />
    <Resource Include="Image\Icon\arrow2_se.gif" />
    <Resource Include="Image\Icon\arrow2_sw.gif" />
    <Resource Include="Image\Icon\arrow2_w.gif" />
    <Resource Include="Image\Icon\arrow3_e.gif" />
    <Resource Include="Image\Icon\arrow3_n.gif" />
    <Resource Include="Image\Icon\arrow3_ne.gif" />
    <Resource Include="Image\Icon\arrow3_nw.gif" />
    <Resource Include="Image\Icon\arrow3_s.gif" />
    <Resource Include="Image\Icon\arrow3_se.gif" />
    <Resource Include="Image\Icon\arrow3_sw.gif" />
    <Resource Include="Image\Icon\arrow3_w.gif" />
    <Resource Include="Image\Icon\arrow_right.gif" />
    <Resource Include="Image\Icon\ascii.gif" />
    <Resource Include="Image\Icon\ascii.png" />
    <Resource Include="Image\Icon\back.gif" />
    <Resource Include="Image\Icon\bigsmile.gif" />
    <Resource Include="Image\Icon\binary.gif" />
    <Resource Include="Image\Icon\blah.gif" />
    <Resource Include="Image\Icon\bstop.gif" />
    <Resource Include="Image\Icon\buy.gif" />
    <Resource Include="Image\Icon\calday.gif" />
    <Resource Include="Image\Icon\calendar.gif" />
    <Resource Include="Image\Icon\camera.gif" />
    <Resource Include="Image\Icon\cart.gif" />
    <Resource Include="Image\Icon\cd.gif" />
    <Resource Include="Image\Icon\cellphone.gif" />
    <Resource Include="Image\Icon\chat.gif" />
    <Resource Include="Image\Icon\check.gif" />
    <Resource Include="Image\Icon\checkout-orange.gif" />
    <Resource Include="Image\Icon\close.gif" />
    <Resource Include="Image\Icon\comment.gif" />
    <Resource Include="Image\Icon\contact-new.png" />
    <Resource Include="Image\Icon\cube.gif" />
    <Resource Include="Image\Icon\database_(edit)_16x16.gif" />
    <Resource Include="Image\Icon\Date-Add.png" />
    <Resource Include="Image\Icon\Date-Delete.png" />
    <Resource Include="Image\Icon\Date-Edit.png" />
    <Resource Include="Image\Icon\Date-Error.png" />
    <Resource Include="Image\Icon\Date-Go.png" />
    <Resource Include="Image\Icon\Date-Link.png" />
    <Resource Include="Image\Icon\Date-Magnify.png" />
    <Resource Include="Image\Icon\Date-Next.png" />
    <Resource Include="Image\Icon\Date-Previous.png" />
    <Resource Include="Image\Icon\date.png" />
    <Resource Include="Image\Icon\date2.gif" />
    <Resource Include="Image\Icon\day.gif" />
    <Resource Include="Image\Icon\DBTable.png" />
    <Resource Include="Image\Icon\delete.png" />
    <Resource Include="Image\Icon\denied.gif" />
    <Resource Include="Image\Icon\Disk.png" />
    <Resource Include="Image\Icon\document-open.png" />
    <Resource Include="Image\Icon\document-save16.png" />
    <Resource Include="Image\Icon\document-save22.png" />
    <Resource Include="Image\Icon\document-save24.png" />
    <Resource Include="Image\Icon\Document-Todo-32.png" />
    <Resource Include="Image\Icon\Document-Todo2-32.png" />
    <Resource Include="Image\Icon\document.gif" />
    <Resource Include="Image\Icon\Documents .png" />
    <Resource Include="Image\Icon\download.gif" />
    <Resource Include="Image\Icon\drive-harddisk.png" />
    <Resource Include="Image\Icon\drive-removable-media.png" />
    <Resource Include="Image\Icon\edit-redo.png" />
    <Resource Include="Image\Icon\edit.gif" />
    <Resource Include="Image\Icon\edit.png" />
    <Resource Include="Image\Icon\eject.gif" />
    <Resource Include="Image\Icon\equalizer.gif" />
    <Resource Include="Image\Icon\exit.png" />
    <Resource Include="Image\Icon\Find.png" />
    <Resource Include="Image\Icon\first.gif" />
    <Resource Include="Image\Icon\flag.gif" />
    <Resource Include="Image\Icon\flash.gif" />
    <Resource Include="Image\Icon\Folder-Add.png" />
    <Resource Include="Image\Icon\Folder-Delete.png" />
    <Resource Include="Image\Icon\Folder-Find.png" />
    <Resource Include="Image\Icon\folder.gif" />
    <Resource Include="Image\Icon\Folder.png" />
    <Resource Include="Image\Icon\forward.gif" />
    <Resource Include="Image\Icon\frown.gif" />
    <Resource Include="Image\Icon\ftp.gif" />
    <Resource Include="Image\Icon\gnome-run.ico" />
    <Resource Include="Image\Icon\go-last.png" />
    <Resource Include="Image\Icon\go-next.png" />
    <Resource Include="Image\Icon\graph.gif" />
    <Resource Include="Image\Icon\heart.gif" />
    <Resource Include="Image\Icon\home.gif" />
    <Resource Include="Image\Icon\Home_icon.png" />
    <Resource Include="Image\Icon\html.gif" />
    <Resource Include="Image\Icon\icon_user.gif" />
    <Resource Include="Image\Icon\icon_wand.gif" />
    <Resource Include="Image\Icon\ico_datemask.png" />
    <Resource Include="Image\Icon\ipod.gif" />
    <Resource Include="Image\Icon\last.gif" />
    <Resource Include="Image\Icon\Layer-Create.png" />
    <Resource Include="Image\Icon\list.png" />
    <Resource Include="Image\Icon\List_Icon.png" />
    <Resource Include="Image\Icon\lock.gif" />
    <Resource Include="Image\Icon\loop.gif" />
    <Resource Include="Image\Icon\mail.gif" />
    <Resource Include="Image\Icon\man.gif" />
    <Resource Include="Image\Icon\manman.gif" />
    <Resource Include="Image\Icon\Monitor-Window-3d.png" />
    <Resource Include="Image\Icon\music.gif" />
    <Resource Include="Image\Icon\mute.gif" />
    <Resource Include="Image\Icon\mute_centered.gif" />
    <Resource Include="Image\Icon\My-Documents-Inside-Green-128.png" />
    <Resource Include="Image\Icon\newwindow.gif" />
    <Resource Include="Image\Icon\next.gif" />
    <Resource Include="Image\Icon\night.gif" />
    <Resource Include="Image\Icon\open.gif" />
    <Resource Include="Image\Icon\pause.gif" />
    <Resource Include="Image\Icon\pdf.png" />
    <Resource Include="Image\Icon\phone.gif" />
    <Resource Include="Image\Icon\play.gif" />
    <Resource Include="Image\Icon\preferences-desktop.png" />
    <Resource Include="Image\Icon\previous.gif" />
    <Resource Include="Image\Icon\quicktime.gif" />
    <Resource Include="Image\Icon\redo.gif" />
    <Resource Include="Image\Icon\reload.gif" />
    <Resource Include="Image\Icon\sad.gif" />
    <Resource Include="Image\Icon\save.gif" />
    <Resource Include="Image\Icon\save16.png" />
    <Resource Include="Image\Icon\save24.png" />
    <Resource Include="Image\Icon\scream.gif" />
    <Resource Include="Image\Icon\search.gif" />
    <Resource Include="Image\Icon\search.png" />
    <Resource Include="Image\Icon\seconds.gif" />
    <Resource Include="Image\Icon\Setting-Tools.png" />
    <Resource Include="Image\Icon\setup.png" />
    <Resource Include="Image\Icon\smile.gif" />
    <Resource Include="Image\Icon\smirk.gif" />
    <Resource Include="Image\Icon\star.gif" />
    <Resource Include="Image\Icon\stop.gif" />
    <Resource Include="Image\Icon\subtract.gif" />
    <Resource Include="Image\Icon\support2_(edit)_16x16.gif" />
    <Resource Include="Image\Icon\switch.gif" />
    <Resource Include="Image\Icon\system-users.png" />
    <Resource Include="Image\Icon\Table-Delete.png" />
    <Resource Include="Image\Icon\target.gif" />
    <Resource Include="Image\Icon\tcp.gif" />
    <Resource Include="Image\Icon\text-x-changelog.png" />
    <Resource Include="Image\Icon\text-x-script.png" />
    <Resource Include="Image\Icon\text-x-source.png" />
    <Resource Include="Image\Icon\TextTemplate.ico" />
    <Resource Include="Image\Icon\time.gif" />
    <Resource Include="Image\Icon\titlewindow.gif" />
    <Resource Include="Image\Icon\toggle.gif" />
    <Resource Include="Image\Icon\tongue.gif" />
    <Resource Include="Image\Icon\tools.gif" />
    <Resource Include="Image\Icon\trackback.gif" />
    <Resource Include="Image\Icon\trash.gif" />
    <Resource Include="Image\Icon\tree.png" />
    <Resource Include="Image\Icon\tv.gif" />
    <Resource Include="Image\Icon\type.gif" />
    <Resource Include="Image\Icon\undo.gif" />
    <Resource Include="Image\Icon\unlock.gif" />
    <Resource Include="Image\Icon\upload.gif" />
    <Resource Include="Image\Icon\user.gif" />
    <Resource Include="Image\Icon\video.gif" />
    <Resource Include="Image\Icon\view_tree.png" />
    <Resource Include="Image\Icon\volume.gif" />
    <Resource Include="Image\Icon\volume_high.gif" />
    <Resource Include="Image\Icon\volume_low.gif" />
    <Resource Include="Image\Icon\Wand.png" />
    <Resource Include="Image\Icon\wifi.gif" />
    <Resource Include="Image\Icon\window.gif" />
    <Resource Include="Image\Icon\woman.gif" />
    <Resource Include="Image\Icon\womanman.gif" />
    <Resource Include="Image\Icon\work.gif" />
    <Resource Include="Image\Icon\zoomin.gif" />
    <Resource Include="Image\Icon\zoomout.gif" />
  </ItemGroup>

</Project>
